const exercises = [
  makeExercise("GT-LAB-01-TERMINAL", "Terminal básica", "Inicio", "Bash", "Crear un espacio de trabajo, generar archivos, guardar una salida y comprobar el resultado.", "Aprender el flujo mínimo de un script: preparar entorno, crear datos, producir salida, verificar y concluir.", [
    step("preparar", "Preparar carpeta de trabajo", "Crear una carpeta para la práctica y entrar en ella.", "Piensa en mkdir y cd.", "mkdir -p laboratorio-terminal\ncd laboratorio-terminal"),
    step("crear", "Crear archivos de prueba", "Crear tres archivos vacíos.", "No necesitas contenido todavía.", "touch uno.txt dos.txt tres.txt"),
    step("salida", "Guardar listado como evidencia", "Guardar el listado en un archivo.", "Usa redirección.", "ls -lah > listado.txt"),
    step("buscar", "Buscar dentro de la evidencia", "Comprobar que aparece uno.txt.", "Busca una palabra concreta dentro del listado.", "grep \"uno\" listado.txt"),
    step("conclusion", "Documentar conclusión", "Añadir una conclusión al informe.", "Explica qué demuestra la evidencia.", "echo \"Conclusion: el listado contiene los archivos creados.\" > informe.md")
  ]),
  makeExercise("GT-LAB-03-WINDOWS", "Windows PowerShell", "Administración", "PowerShell", "Generar un informe simple de un equipo Windows.", "Construir un script con sistema, disco, procesos, servicios y salida a informe.", [
    step("sistema", "Identificar equipo", "Obtener equipo y usuario.", "Empieza sabiendo qué equipo revisas.", "$equipo = $env:COMPUTERNAME\n$usuario = $env:USERNAME"),
    step("disco", "Revisar disco", "Consultar unidades disponibles.", "Get-PSDrive filtra unidades del sistema de archivos.", "$discos = Get-PSDrive -PSProvider FileSystem"),
    step("procesos", "Revisar procesos", "Obtener procesos con más CPU.", "Ordenar ayuda a encontrar antes lo importante.", "$procesos = Get-Process | Sort-Object CPU -Descending | Select-Object -First 5"),
    step("servicios", "Revisar servicios", "Consultar servicios en ejecución.", "Filtra por Status.", "$servicios = Get-Service | Where-Object Status -eq 'Running' | Select-Object -First 10"),
    step("salida", "Crear informe", "Guardar resultados en un archivo.", "Out-File deja evidencia.", "$equipo, $usuario, $discos, $procesos, $servicios | Out-File informe-windows.txt")
  ]),
  makeExercise("GT-LAB-04-REDES", "Diagnóstico de redes", "Redes", "Bash", "Un equipo parece tener problemas de conexión.", "Construir un diagnóstico por capas: IP, gateway, DNS, puerto y conclusión.", [
    step("ip", "Comprobar IP local", "Mostrar la configuración IP.", "Primero confirma si hay IP local.", "ip address show"),
    step("gateway", "Comprobar gateway", "Mostrar ruta por defecto.", "Sin gateway puede no haber salida a otras redes.", "ip route show default"),
    step("dns", "Comprobar DNS", "Probar resolución de nombres.", "Si la IP funciona pero el nombre no, sospecha DNS.", "nslookup example.com"),
    step("puerto", "Comprobar puerto web", "Probar si un servicio web responde.", "curl -I muestra cabeceras HTTP.", "curl -I https://example.com"),
    step("conclusion", "Redactar diagnóstico", "Guardar conclusión técnica.", "Indica la capa probable del fallo.", "echo \"Conclusion: revisar IP, gateway, DNS y puerto.\" > diagnostico-red.md")
  ]),
  makeExercise("GT-LAB-06-SCRIPTING", "Scripting aplicado", "Automatización", "Bash", "Crear un script que recibe una carpeta, comprueba si existe y genera un informe.", "Entender cabecera, entrada, condición, proceso, salida y verificación.", [
    step("objetivo", "Cabecera y objetivo", "Iniciar el script y explicar su finalidad.", "La cabecera indica intérprete.", "#!/usr/bin/env bash\n# Objetivo: generar un informe de una carpeta"),
    step("entrada", "Recibir entrada", "Leer carpeta desde el primer argumento.", "En Bash, $1 es el primer argumento.", "CARPETA=\"$1\"\nINFORME=\"informe-carpeta.txt\""),
    step("condicion", "Validar entrada", "Comprobar que la carpeta existe.", "Valida antes de actuar.", "if [ ! -d \"$CARPETA\" ]; then\n  echo \"Error: la carpeta no existe\"\n  exit 1\nfi"),
    step("proceso", "Procesar información", "Listar contenido de la carpeta.", "Acción principal del script.", "ls -lah \"$CARPETA\" > \"$INFORME\""),
    step("verificacion", "Verificar salida", "Confirmar que se creó el informe.", "No des por hecho que existe.", "if [ -f \"$INFORME\" ]; then\n  echo \"Informe generado: $INFORME\"\nfi")
  ]),
  makeExercise("PY-LAB-01-INVENTARIO", "Python inventario de carpeta", "Python inicio", "Python", "Recibir una carpeta, revisarla y generar un informe de archivos.", "Practicar pathlib, argumentos, validación, recorrido y escritura.", [
    step("objetivo", "Importar módulos", "Preparar módulos necesarios.", "pathlib trabaja bien con rutas.", "from pathlib import Path\nimport sys\n\n# Objetivo: generar un inventario simple"),
    step("entrada", "Recibir ruta", "Leer carpeta desde argumento.", "sys.argv[1] contiene el primer argumento real.", "carpeta = Path(sys.argv[1])\ninforme = Path(\"inventario.txt\")"),
    step("condicion", "Validar carpeta", "Comprobar que existe y es carpeta.", "Evita errores confusos.", "if not carpeta.is_dir():\n    print(\"Error: la carpeta no existe\")\n    sys.exit(1)"),
    step("proceso", "Recorrer archivos", "Crear líneas de inventario.", "iterdir recorre el contenido directo.", "lineas = []\nfor ruta in carpeta.iterdir():\n    if ruta.is_file():\n        lineas.append(f\"{ruta.name} - {ruta.stat().st_size} bytes\")"),
    step("salida", "Guardar informe", "Escribir salida en texto.", "write_text guarda el contenido completo.", "informe.write_text(\"\\n\".join(lineas), encoding=\"utf-8\")\nprint(f\"Informe generado: {informe}\")")
  ]),
  makeExercise("PY-LAB-02-CSV", "Python análisis de CSV", "Python administración", "Python", "Generar resumen desde un CSV de usuarios.", "Practicar csv, listas, filtros, condiciones y salida.", [
    step("objetivo", "Preparar lectura CSV", "Importar módulos y definir archivos.", "csv evita separar columnas manualmente.", "import csv\nfrom pathlib import Path\n\nentrada = Path(\"usuarios.csv\")\nsalida = Path(\"resumen-usuarios.txt\")"),
    step("condicion", "Validar entrada", "Comprobar que el CSV existe.", "Termina con mensaje claro si no existe.", "if not entrada.is_file():\n    print(\"Error: no existe usuarios.csv\")\n    raise SystemExit(1)"),
    step("proceso", "Leer registros", "Leer CSV como diccionario.", "DictReader accede por nombre de columna.", "with entrada.open(newline=\"\", encoding=\"utf-8\") as archivo:\n    registros = list(csv.DictReader(archivo))"),
    step("buscar", "Filtrar activos", "Listar usuarios activos.", "Compara columna estado.", "activos = [fila[\"usuario\"] for fila in registros if fila.get(\"estado\") == \"activo\"]"),
    step("salida", "Guardar resumen", "Crear informe de texto.", "Convierte resultados a texto claro.", "contenido = f\"Total: {len(registros)}\\nActivos: {', '.join(activos)}\\n\"\nsalida.write_text(contenido, encoding=\"utf-8\")\nprint(\"Resumen generado\")")
  ]),
  makeExercise("PY-LAB-03-PUERTOS", "Python comprobador de puertos", "Python redes", "Python", "Comprobar si un host responde en un puerto concreto dentro de un laboratorio.", "Practicar argumentos, sockets, timeout, errores y salida clara.", [
    step("objetivo", "Preparar script de red", "Importar módulos.", "socket permite conexiones TCP simples.", "import socket\nimport sys\n\n# Uso: python comprobar_puerto.py HOST PUERTO"),
    step("entrada", "Leer host y puerto", "Obtener parámetros desde argumentos.", "Convierte el puerto a entero.", "host = sys.argv[1]\npuerto = int(sys.argv[2])\ntimeout = 3"),
    step("proceso", "Crear conexión", "Intentar conectar con timeout.", "create_connection falla si no responde.", "try:\n    with socket.create_connection((host, puerto), timeout=timeout):\n        abierto = True\nexcept OSError:\n    abierto = False"),
    step("condicion", "Interpretar resultado", "Mostrar mensaje según estado.", "Convierte resultado técnico en salida legible.", "if abierto:\n    print(f\"OK: {host}:{puerto} responde\")\nelse:\n    print(f\"ERROR: {host}:{puerto} no responde\")"),
    step("conclusion", "Uso responsable", "Documentar uso en laboratorio.", "La documentación también es parte profesional.", "# Conclusion: usar solo en equipos propios, laboratorio o sistemas con permiso.")
  ]),
  makeExercise("PRO-BASH-01-BACKUP", "Bash backup profesional", "Profesional", "Bash", "Crear un backup con fecha, log, validación, dry-run y verificación.", "Practicar estructura senior de automatización segura.", [
    step("objetivo", "Cabecera estricta", "Activar modo estricto y documentar uso.", "set -euo pipefail evita muchos errores silenciosos.", "#!/usr/bin/env bash\nset -euo pipefail\n# Uso: ./backup_pro.sh ORIGEN DESTINO [--dry-run]"),
    step("entrada", "Parámetros", "Leer origen, destino y dry-run.", "Usa valores por defecto para opciones.", "ORIGEN=\"${1:-}\"\nDESTINO=\"${2:-}\"\nDRY_RUN=\"${3:-false}\""),
    step("logging", "Función de log", "Crear una función de registro.", "El log debe incluir fecha y hora.", "LOG=\"backup.log\"\nlog() { echo \"$(date '+%F %T') $*\" | tee -a \"$LOG\"; }"),
    step("condicion", "Validar entrada", "Comprobar origen y destino.", "Valida antes de copiar.", "if [ ! -d \"$ORIGEN\" ]; then\n  log \"ERROR: origen no existe\"\n  exit 1\nfi\nmkdir -p \"$DESTINO\""),
    step("dryrun", "Modo dry-run", "Simular antes de copiar.", "Un script profesional permite ver qué haría.", "if [ \"$DRY_RUN\" = \"--dry-run\" ]; then\n  log \"DRY-RUN: se copiaría $ORIGEN a $DESTINO\"\n  exit 0\nfi"),
    step("proceso", "Ejecutar backup", "Crear archivo comprimido con fecha.", "La fecha evita sobrescribir copias anteriores.", "ARCHIVO=\"$DESTINO/backup-$(date +%F-%H%M).tar.gz\"\ntar -czf \"$ARCHIVO\" -C \"$ORIGEN\" ."),
    step("verificacion", "Verificar backup", "Comprobar que el archivo existe.", "Sin verificación no hay backup fiable.", "if [ -f \"$ARCHIVO\" ]; then\n  log \"Backup generado: $ARCHIVO\"\nfi")
  ]),
  makeExercise("PRO-PY-01-ARGPARSE", "Python argparse y logging", "Profesional", "Python", "Convertir un script básico en herramienta profesional con argparse, logging y códigos de salida.", "Practicar CLI robusta, validación, logs y main().", [
    step("objetivo", "Estructura main", "Preparar imports y función main.", "Los scripts mantenibles separan definición y ejecución.", "import argparse\nimport logging\nfrom pathlib import Path\n\ndef main():\n    pass\n\nif __name__ == \"__main__\":\n    raise SystemExit(main())"),
    step("entrada", "Argumentos CLI", "Definir argumentos con argparse.", "argparse genera ayuda automática.", "parser = argparse.ArgumentParser(description=\"Inventario profesional\")\nparser.add_argument(\"carpeta\", type=Path)\nparser.add_argument(\"--salida\", type=Path, default=Path(\"inventario.md\"))\nparser.add_argument(\"--dry-run\", action=\"store_true\")\nargs = parser.parse_args()"),
    step("logging", "Configurar logging", "Registrar actividad del script.", "logging permite niveles y formato profesional.", "logging.basicConfig(level=logging.INFO, format=\"%(asctime)s %(levelname)s %(message)s\")\nlogging.info(\"Iniciando inventario\")"),
    step("condicion", "Validar carpeta", "Comprobar entrada antes de procesar.", "Devuelve código no cero si hay error.", "if not args.carpeta.is_dir():\n    logging.error(\"La carpeta no existe: %s\", args.carpeta)\n    return 1"),
    step("dryrun", "Simulación", "Mostrar qué se haría sin escribir.", "dry-run es clave antes de cambios reales.", "if args.dry_run:\n    logging.info(\"DRY-RUN: se generaría %s\", args.salida)\n    return 0"),
    step("salida", "Salida Markdown", "Generar informe documentado.", "Markdown es fácil de leer y versionar.", "lineas = [\"# Inventario\", \"\"]\nfor ruta in args.carpeta.iterdir():\n    lineas.append(f\"- {ruta.name}\")\nargs.salida.write_text(\"\\n\".join(lineas), encoding=\"utf-8\")\nreturn 0")
  ]),
  makeExercise("PRO-PS-01-SERVICIOS", "PowerShell servicios con log", "Profesional", "PowerShell", "Revisar servicios críticos, generar log e informe.", "Practicar parámetros, validación, registros y salida operativa.", [
    step("entrada", "Parámetros", "Definir servicios e informe.", "param hace el script reutilizable.", "param(\n  [string[]]$Servicios = @(\"Spooler\", \"WinRM\"),\n  [string]$Informe = \"servicios.md\"\n)"),
    step("logging", "Función de log", "Crear registro con fecha.", "Una función evita repetir formato.", "function Write-Log {\n  param([string]$Mensaje)\n  \"$(Get-Date -Format s) $Mensaje\" | Tee-Object -FilePath script.log -Append\n}"),
    step("proceso", "Revisar servicios", "Consultar cada servicio.", "Get-Service puede fallar si el nombre no existe.", "$resultados = foreach ($nombre in $Servicios) {\n  Get-Service -Name $nombre -ErrorAction SilentlyContinue\n}"),
    step("condicion", "Detectar faltantes", "Avisar si un servicio no existe.", "Un informe debe distinguir parado, activo y no encontrado.", "foreach ($nombre in $Servicios) {\n  if (-not ($resultados | Where-Object Name -eq $nombre)) { Write-Log \"Servicio no encontrado: $nombre\" }\n}"),
    step("salida", "Generar informe", "Exportar estado a Markdown.", "La evidencia debe quedar guardada.", "$resultados | Select-Object Name, Status | Out-File $Informe\nWrite-Log \"Informe generado: $Informe\"")
  ]),
  makeExercise("PRO-PY-02-PUERTOS-CSV", "Python puertos desde CSV", "Profesional redes", "Python", "Leer una lista de hosts y puertos desde CSV y generar resultados.", "Practicar automatización de red defensiva con entrada estructurada y salida CSV.", [
    step("objetivo", "Preparar módulos", "Importar csv, socket y pathlib.", "Usa librerías estándar.", "import csv\nimport socket\nfrom pathlib import Path"),
    step("entrada", "Definir archivos", "Elegir CSV de entrada y salida.", "Separar entrada/salida mejora mantenimiento.", "entrada = Path(\"objetivos.csv\")\nsalida = Path(\"resultado-puertos.csv\")\ntimeout = 2"),
    step("proceso", "Función comprobar", "Crear función para probar un puerto.", "Una función permite reutilizar la lógica.", "def comprobar(host, puerto):\n    try:\n        with socket.create_connection((host, int(puerto)), timeout=timeout):\n            return \"abierto\"\n    except OSError:\n        return \"cerrado\""),
    step("proceso", "Procesar CSV", "Leer objetivos y comprobar cada uno.", "Cada fila debe tener host y puerto.", "resultados = []\nwith entrada.open(newline=\"\", encoding=\"utf-8\") as f:\n    for fila in csv.DictReader(f):\n        estado = comprobar(fila[\"host\"], fila[\"puerto\"])\n        resultados.append({**fila, \"estado\": estado})"),
    step("salida", "Guardar resultados", "Exportar CSV final.", "DictWriter genera CSV reutilizable.", "with salida.open(\"w\", newline=\"\", encoding=\"utf-8\") as f:\n    writer = csv.DictWriter(f, fieldnames=[\"host\", \"puerto\", \"estado\"])\n    writer.writeheader()\n    writer.writerows(resultados)"),
    step("conclusion", "Uso responsable", "Documentar alcance autorizado.", "Nunca automatices pruebas fuera del laboratorio o sin permiso.", "# Uso responsable: ejecutar solo sobre hosts propios, laboratorio o sistemas con autorización.")
  ]),
  makeExercise("PRO-BASH-02-LIMPIEZA", "Bash limpieza segura", "Profesional", "Bash", "Limpiar archivos temporales antiguos sin asumir riesgos.", "Practicar dry-run, confirmación, logs y seguridad en scripts destructivos.", [
    step("objetivo", "Cabecera segura", "Activar modo estricto y documentar uso.", "La limpieza es delicada: documenta antes.", "#!/usr/bin/env bash\nset -euo pipefail\n# Uso: ./limpieza.sh CARPETA DIAS [--dry-run]"),
    step("entrada", "Leer parámetros", "Recibir carpeta, días y modo.", "No uses rutas fijas para acciones peligrosas.", "CARPETA=\"${1:-}\"\nDIAS=\"${2:-30}\"\nMODO=\"${3:-}\""),
    step("condicion", "Validar carpeta", "Evitar rutas vacías o raíz.", "Nunca limpies / por error.", "if [ -z \"$CARPETA\" ] || [ \"$CARPETA\" = \"/\" ]; then\n  echo \"Error: carpeta no permitida\"\n  exit 1\nfi"),
    step("dryrun", "Simular limpieza", "Mostrar qué se borraría.", "Primero mirar, después actuar.", "if [ \"$MODO\" = \"--dry-run\" ]; then\n  find \"$CARPETA\" -type f -mtime +\"$DIAS\" -print\n  exit 0\nfi"),
    step("confirmacion", "Confirmar acción", "Pedir confirmación explícita.", "Un borrado profesional requiere confirmación.", "read -r -p \"¿Borrar archivos antiguos? escribe SI: \" RESPUESTA\nif [ \"$RESPUESTA\" != \"SI\" ]; then\n  echo \"Cancelado\"\n  exit 0\nfi"),
    step("proceso", "Ejecutar limpieza", "Eliminar archivos antiguos.", "Solo tras validación y confirmación.", "find \"$CARPETA\" -type f -mtime +\"$DIAS\" -delete\necho \"Limpieza finalizada\"")
  ])
];

function makeExercise(id, title, level, language, scenario, goal, steps) { return { id, title, level, language, scenario, goal, steps }; }
function step(type, title, task, hint, code) { return { type, title, task, hint, code }; }

const blockInfo = {
  objetivo: { label: "Objetivo", help: "Define la finalidad del script." }, preparar: { label: "Preparar", help: "Prepara entorno de trabajo." }, entrada: { label: "Entrada", help: "Recoge argumentos o parámetros." }, crear: { label: "Crear", help: "Crea archivos, carpetas o recursos." }, variable: { label: "Variable", help: "Guarda datos reutilizables." }, condicion: { label: "Condición", help: "Toma decisiones según una comprobación." }, proceso: { label: "Proceso", help: "Ejecuta la acción principal." }, salida: { label: "Salida", help: "Muestra o guarda resultados." }, buscar: { label: "Buscar", help: "Localiza información concreta." }, verificacion: { label: "Verificación", help: "Comprueba que el resultado es válido." }, sistema: { label: "Sistema", help: "Obtiene información del equipo." }, disco: { label: "Disco", help: "Revisa unidades y espacio." }, procesos: { label: "Procesos", help: "Consulta procesos activos." }, servicios: { label: "Servicios", help: "Consulta servicios del sistema." }, logs: { label: "Logs", help: "Revisa registros o eventos." }, red: { label: "Red", help: "Comprueba conectividad general." }, ip: { label: "IP", help: "Comprueba dirección IP local." }, gateway: { label: "Gateway", help: "Comprueba puerta de enlace." }, dns: { label: "DNS", help: "Comprueba resolución de nombres." }, puerto: { label: "Puerto", help: "Comprueba puertos o servicios remotos." }, conclusion: { label: "Conclusión", help: "Interpreta el resultado." }, logging: { label: "Logging", help: "Registra actividad y errores." }, dryrun: { label: "Dry-run", help: "Simula antes de ejecutar cambios." }, confirmacion: { label: "Confirmación", help: "Pide aprobación antes de acciones críticas." }
};

const patterns = [
  { type: "logging", words: ["logging", "log()", "write-log", "script.log", "tee -a"] }, { type: "dryrun", words: ["dry-run", "DRY_RUN", "simular"] }, { type: "confirmacion", words: ["read -r -p", "confirm", "respuesta"] }, { type: "objetivo", words: ["#!/", "objetivo", "finalidad", "import ", "from "] }, { type: "preparar", words: ["mkdir", "cd ", "set-location"] }, { type: "entrada", words: ["$1", "sys.argv", "argparse", "param(", "param", "argumento", "entrada"] }, { type: "crear", words: ["touch", "new-item", "crear"] }, { type: "variable", words: ["=", "$equipo", "$usuario", "CARPETA="] }, { type: "condicion", words: ["if ", "then", "else", "where-object", "except", "not "] }, { type: "buscar", words: ["grep", "select-string", "findstr", "activos", "join"] }, { type: "verificacion", words: ["-f", "test-path", "verificar", "is_file", "is_dir"] }, { type: "sistema", words: ["computername", "username", "hostname", "whoami"] }, { type: "disco", words: ["get-psdrive", "df", "disco"] }, { type: "procesos", words: ["get-process", "ps ", "top"] }, { type: "servicios", words: ["get-service", "systemctl", "servicio"] }, { type: "ip", words: ["ip address", "ipconfig", "get-netipaddress"] }, { type: "gateway", words: ["ip route", "route print", "gateway"] }, { type: "dns", words: ["nslookup", "resolve-dnsname", "dns"] }, { type: "puerto", words: ["curl", "test-netconnection", "443", "80", "socket", "puerto"] }, { type: "salida", words: [">", "out-file", "echo", "print", "write_text", "writerow", "informe"] }, { type: "conclusion", words: ["conclusion", "diagnostico", "recomendacion", "permiso"] }, { type: "proceso", words: ["ls ", "for ", "with ", "tar ", "find ", "copy-item", "create_connection"] }
];

const qualityChecks = [
  { id: "cabecera", label: "Cabecera/objetivo", words: ["#!/", "objetivo", "description"] }, { id: "parametros", label: "Parámetros", words: ["$1", "argparse", "param(", "sys.argv"] }, { id: "validacion", label: "Validación", words: ["if ", "is_dir", "is_file", "test-path", "exit 1", "return 1"] }, { id: "logging", label: "Logging", words: ["logging", "log()", "write-log", "script.log", "tee -a"] }, { id: "errores", label: "Gestión de errores", words: ["try:", "except", "error", "raise systemexit", "exit 1"] }, { id: "dryrun", label: "Dry-run", words: ["dry-run", "DRY_RUN", "simular"] }, { id: "salida", label: "Salida/evidencia", words: ["out-file", "write_text", ">", "informe", "csv", "markdown"] }, { id: "seguridad", label: "Seguridad", words: ["set -euo pipefail", "permiso", "confirm", "read -r -p", "validar"] }, { id: "resumen", label: "Conclusión/resumen", words: ["conclusion", "diagnostico", "recomendacion", "resumen"] }
];

const exerciseSelect = document.getElementById("exerciseSelect"), exerciseInfo = document.getElementById("exerciseInfo"), stepsOutput = document.getElementById("stepsOutput"), solutionInput = document.getElementById("solutionInput"), analyzeBtn = document.getElementById("analyzeBtn"), exampleBtn = document.getElementById("exampleBtn"), clearBtn = document.getElementById("clearBtn"), blocksOutput = document.getElementById("blocksOutput"), feedbackOutput = document.getElementById("feedbackOutput"), exportOutput = document.getElementById("exportOutput"), qualityOutput = document.getElementById("qualityOutput");

function init() { exercises.forEach((exercise, index) => { const option = document.createElement("option"); option.value = index; option.textContent = `${exercise.id} - ${exercise.title}`; exerciseSelect.appendChild(option); }); const requested = getExerciseFromUrl(); if (requested) { const index = exercises.findIndex(exercise => exercise.id === requested); if (index >= 0) exerciseSelect.value = String(index); } renderExercise(); analyze(); }
function getExerciseFromUrl() { const value = new URLSearchParams(window.location.search).get("exercise") || new URLSearchParams(window.location.search).get("id"); if (!value) return null; const normalized = value.trim().toUpperCase(); return /^[A-Z]+-LAB-\d{2}-[A-Z0-9-]+$|^PRO-[A-Z]+-\d{2}-[A-Z0-9-]+$|^GT-LAB-\d{2}-[A-Z0-9-]+$/.test(normalized) ? normalized : null; }
function selectedExercise() { return exercises[Number(exerciseSelect.value || 0)]; }
function renderExercise() { const exercise = selectedExercise(); const url = new URL(window.location.href); url.searchParams.set("exercise", exercise.id); window.history.replaceState({}, "", url.toString()); exerciseInfo.innerHTML = `<h3>${escapeHtml(exercise.title)}</h3><p><strong>Nivel:</strong> ${escapeHtml(exercise.level)}</p><p><strong>Lenguaje:</strong> ${escapeHtml(exercise.language)}</p><p><strong>Escenario:</strong> ${escapeHtml(exercise.scenario)}</p><p><strong>Objetivo:</strong> ${escapeHtml(exercise.goal)}</p>`; stepsOutput.innerHTML = exercise.steps.map((s, i) => `<article class="step-card block-${escapeHtml(s.type)}"><div class="step-number">${i + 1}</div><div class="step-content"><div class="step-header"><span class="block-pill">${escapeHtml(labelFor(s.type))}</span><h3>${escapeHtml(s.title)}</h3></div><p><strong>Qué tienes que hacer:</strong> ${escapeHtml(s.task)}</p><details><summary>Pista si me bloqueo</summary><p>${escapeHtml(s.hint)}</p></details><details class="advanced-help"><summary>Ver código real si sigo bloqueado</summary><p>Consulta este código solo después de intentar construir el bloque por tu cuenta.</p><pre class="code-preview"><code>${escapeHtml(s.code)}</code></pre></details><button class="add-block" data-step="${i}">Añadir bloque al script</button></div></article>`).join(""); document.querySelectorAll(".add-block").forEach(b => b.addEventListener("click", () => addStepToWorkspace(Number(b.dataset.step)))); }
function addStepToWorkspace(index) { const step = selectedExercise().steps[index]; solutionInput.value = `${solutionInput.value}\n\n# BLOQUE ${index + 1}: ${step.title}\n${step.code}`.trimStart(); analyze(); }
function loadGuidedSolution() { const ex = selectedExercise(); solutionInput.value = ex.steps.map((s, i) => `# BLOQUE ${i + 1}: ${s.title}\n${s.code}`).join("\n\n"); analyze(); }
function analyze() { const chunks = splitIntoBlocks(solutionInput.value); const blocks = chunks.map((chunk, index) => buildVisualBlock(chunk, index)); renderBlocks(blocks); renderQuality(solutionInput.value); renderFeedback(blocks); renderExport(blocks); }
function splitIntoBlocks(text) { const lines = text.split("\n"); const chunks = []; let current = []; lines.forEach(line => { if (/^#\s*BLOQUE/i.test(line) && current.length) { chunks.push(current.join("\n").trim()); current = [line]; } else if (line.trim() || current.length) current.push(line); }); if (current.join("\n").trim()) chunks.push(current.join("\n").trim()); return chunks; }
function buildVisualBlock(chunk, index) { const type = detectType(chunk); const info = blockInfo[type] || blockInfo.proceso; return { number: index + 1, type, label: info.label, help: info.help, code: chunk, warnings: buildWarnings(chunk) }; }
function detectType(text) { const normalized = normalize(text); const found = patterns.find(pattern => pattern.words.some(word => normalized.includes(normalize(word)))); return found ? found.type : "proceso"; }
function buildWarnings(chunk) { const w = []; if (chunk.length < 12) w.push("Bloque demasiado corto; añade código o comentario."); if (/rm -rf|format|delete|del /i.test(chunk)) w.push("Acción destructiva: exige laboratorio, validación y confirmación."); if (!/#|echo|write-output|out-file|>|print|write_text|logging|log/.test(chunk)) w.push("Añade comentario, salida, log o evidencia."); return w; }
function renderBlocks(blocks) { if (!blocks.length) { blocksOutput.innerHTML = `<div class="empty-state">Añade bloques desde los pasos o escribe código en el editor.</div>`; return; } blocksOutput.innerHTML = blocks.map(b => `<article class="visual-block block-${escapeHtml(b.type)}"><div class="block-number">${b.number}</div><div class="block-body"><div class="block-head"><strong>${escapeHtml(b.label)}</strong><span>${escapeHtml(b.type)}</span></div><p class="block-help">${escapeHtml(b.help)}</p><pre class="block-code"><code>${escapeHtml(b.code)}</code></pre>${b.warnings.length ? `<ul class="block-warnings">${b.warnings.map(x => `<li>${escapeHtml(x)}</li>`).join("")}</ul>` : ""}</div></article>`).join("<div class='connector'>↓</div>"); }
function renderQuality(text) { const normalized = normalize(text); const passed = qualityChecks.filter(c => c.words.some(w => normalized.includes(normalize(w)))); const score = Math.round((passed.length / qualityChecks.length) * 100); qualityOutput.innerHTML = `<div class="quality-score"><strong>${score}%</strong><span>madurez profesional</span></div><ul>${qualityChecks.map(c => `<li class="${passed.includes(c) ? "ok" : "missing"}">${passed.includes(c) ? "✓" : "□"} ${escapeHtml(c.label)}</li>`).join("")}</ul>`; }
function renderFeedback(blocks) { const expected = selectedExercise().steps.map(s => s.type); const found = new Set(blocks.map(b => b.type)); const missing = expected.filter(type => !found.has(type)); const warnings = blocks.flatMap(b => b.warnings); feedbackOutput.innerHTML = `<p class="ok"><strong>Bloques creados:</strong> ${blocks.length}/${selectedExercise().steps.length}</p>${missing.length ? `<p class="missing"><strong>Faltan tipos de bloque:</strong> ${missing.map(labelFor).map(escapeHtml).join(", ")}</p>` : `<p class="ok">La estructura mínima está completa.</p>`}${warnings.length ? `<p class="missing"><strong>Avisos:</strong> ${warnings.length} mejora(s) pendiente(s).</p>` : ""}<h3>Consejo</h3><p>${missing.length ? "Añade los bloques pendientes y revisa la calidad profesional." : "Prueba el script en laboratorio y añade evidencias al informe."}</p>`; }
function renderExport(blocks) { const ex = selectedExercise(); const content = blocks.map(b => `## Bloque ${b.number} - ${b.label}\n\n\`\`\`${ex.language.toLowerCase()}\n${b.code}\n\`\`\``).join("\n\n"); exportOutput.textContent = `# Entrega Script-Lab - ${ex.id}\n\n## Ejercicio\n${ex.title}\n\n## Escenario\n${ex.scenario}\n\n## Objetivo\n${ex.goal}\n\n${content || "Pendiente de construir"}\n\n## Evidencias\n- Pega aquí la salida de la ejecución.\n- Explica errores encontrados.\n- Indica si se probó en dry-run.\n- Escribe una conclusión técnica.\n`; }
function labelFor(type) { return blockInfo[type] ? blockInfo[type].label : type; }
function normalize(value) { return String(value).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function escapeHtml(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }

analyzeBtn.addEventListener("click", analyze); solutionInput.addEventListener("input", analyze); exampleBtn.addEventListener("click", loadGuidedSolution); clearBtn.addEventListener("click", () => { solutionInput.value = ""; analyze(); }); exerciseSelect.addEventListener("change", () => { renderExercise(); solutionInput.value = ""; analyze(); }); init();
